### ISSUE TITLE
InstallGitHooks gradle task on windows not working

### ISSUE THREAD

**Issue by MahdiPorkar-github** [AdamMc331/AndroidAppTemplate#163] opened 2024-04-20 17:28 UTC
I know a way to installGitHooks on Windows too.
check this article
[https://emmanuelkehinde.io/setting-up-git-pre-commit-pre-push-hook-for-ktlint-check/](javascript:void(0);)

**Comment by AdamMc331** [comment] 2024-04-22 01:22
Thanks! I'm gonna close this as a dupe of #51 but I'll bring over your comment. I can revisit this next week, currently traveling & don't have a windows PC to test on.

**Closed as completed by AdamMc331** 2024-04-22 01:22 UTC
